services:
  lightrag:
    container_name: lightrag
    image: ghcr.io/hkuds/lightrag:latest
    ports:
      - "9621:9621"  # Default LightRAG port
    volumes:
      - ./data/rag_storage:/app/data/rag_storage
      - ./data/inputs:/app/data/inputs
      - ./config.ini:/app/config.ini
      - .env:/app/.env
    env_file:
      - .env
    environment:
      - NEO4J_URI=bolt://neo4j-rag:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=password
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - court_net
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9621/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
  neo4j:
    image: neo4j:5.15-community
    container_name: neo4j-rag
    environment:
      NEO4J_AUTH: neo4j/password  # Change this to a secure password
      NEO4J_PLUGINS: '["apoc", "graph-data-science"]'  # Optional: useful plugins
      NEO4J_dbms_memory_heap_initial__size: 512m
      NEO4J_dbms_memory_heap_max__size: 2G
      NEO4J_dbms_memory_pagecache_size: 512m
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    networks:
      - court_net
    healthcheck:
      test: ["CMD-SHELL", "cypher-shell -u neo4j -p password 'RETURN 1'"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

#   ollama:
#     image: docker.io/ollama/ollama:latest
#     ports:
#       - 11434:11434
#     volumes:
#       - .:/code
#       - ./ollama/ollama:/root/.ollama
#     container_name: ollama
#     # ... other ollama configurations ...
#     networks:
#       - court_net
# #   PostgreSQL Database

# # Network configuration
networks:
  court_net:
    driver: bridge

# # Volumes for persistent data
volumes:
  lightrag_data:
    driver: local
#   document_store:
#     driver: local
  neo4j_data:
    driver: local
  neo4j_logs:
    driver: local
  neo4j_import:
    driver: local
  neo4j_plugins:
    driver: local
  # pgdata:
  #   driver: local
#   llm_models:
#     driver: local
