[project]
name = "llm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    # FastApi
    "fastapi>=0.115.12",
    "uvicorn[standard]>=0.29.0",
    "python-multipart>=0.0.7",
    # Model and embeddings
    "sentence-transformers[all]>=4.1.0",
    # Data handling
    "numpy>=2.0.0,<2.2.6",
    "pydantic>=2.11.5",
    "instructor>=1.8.3",
    "httpx>=0.28.1",
]

[project.optional-dependencies]
# Additional dependencies for development and testing
dev = [
    "pytest>=7.0.0",
    "black>=23.0.0",
    "isort>=5.0.0",
    "mypy>=1.0.0"
]
