[project]
name = "lightrag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.12",
    "protobuf>=6.30.0",
    "pydantic>=2.11.5",
    "pypdf>=5.6.0",
    "python-dotenv>=1.1.0",
    "python-multipart>=0.0.20",
    "unstructured>=0.17.2",
    "uvicorn>=0.34.3",
]
